# Generated by Django 3.2.15 on 2022-10-28 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_auto_20220919_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodRecommendation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.food',),
        ),
        migrations.AddField(
            model_name='food',
            name='reported_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
