# Generated by Django 3.2.15 on 2022-11-02 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20221028_0754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='reported_by',
        ),
    ]
